logging:
  level:
    org:
      hibernate: INFO
  file:
    name: /skillbox/final proj/my proj/searchengine/logs/spring_app_log_file.log
    max-size: 300MB
debug: false

server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
    #       name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

jsoup-settings:
  userAgent: "Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
  referer: "http://www.google.com"

search-result-settings:
  defaultSearchResultLimit: 20
  searchPageCountLimit: 2500
  searchPageStartCountLimit: 4000
  searchLemmasCountForPageLimit: 3
  snippetMaxSize: 180
  snippetPartSize: 30

localTimeZone: "+00:00"